-- MySQL Script generated by MySQL Workbench
-- 02/22/16 18:24:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema powerliftersdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `powerliftersdb` ;

-- -----------------------------------------------------
-- Schema powerliftersdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `powerliftersdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `powerliftersdb` ;

-- -----------------------------------------------------
-- Table `powerliftersdb`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`city` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`city` (
  `city_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `city_UNIQUE` ON `powerliftersdb`.`city` (`city_name` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`country` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`country` (
  `country_id` INT UNSIGNED NOT NULL,
  `country_name` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `country_UNIQUE` ON `powerliftersdb`.`country` (`country_name` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`powerlifter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`powerlifter` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`powerlifter` (
  `powerlifter_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL DEFAULT '',
  `first_name` VARCHAR(25) NOT NULL DEFAULT '',
  `sex` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `birthdate` DATE NOT NULL DEFAULT 1970-01-01 00:00:00,
  `city_id` INT UNSIGNED NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`powerlifter_id`),
  CONSTRAINT `fk_powerlifter_city2`
    FOREIGN KEY (`city_id`)
    REFERENCES `powerliftersdb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_powerlifter_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `powerliftersdb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_powerlifter_city2_idx` ON `powerliftersdb`.`powerlifter` (`city_id` ASC);

CREATE INDEX `fk_powerlifter_country1_idx` ON `powerliftersdb`.`powerlifter` (`country_id` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`federation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`federation` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`federation` (
  `federation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `federation_name` VARCHAR(50) NOT NULL,
  `equipment` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`federation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `powerliftersdb`.`competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`competition` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`competition` (
  `competition_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `competition_name` VARCHAR(255) NOT NULL DEFAULT '',
  `start_date` DATE NOT NULL DEFAULT 1970-01-01,
  `end_date` DATE NOT NULL DEFAULT 1970-01-01,
  `federation_id` INT UNSIGNED NOT NULL,
  `country_id` INT UNSIGNED NOT NULL,
  `city_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`competition_id`),
  CONSTRAINT `fk_competition_federation1`
    FOREIGN KEY (`federation_id`)
    REFERENCES `powerliftersdb`.`federation` (`federation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competition_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `powerliftersdb`.`country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competition_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `powerliftersdb`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_competition_federation1_idx` ON `powerliftersdb`.`competition` (`federation_id` ASC);

CREATE INDEX `fk_competition_country1_idx` ON `powerliftersdb`.`competition` (`country_id` ASC);

CREATE INDEX `fk_competition_city1_idx` ON `powerliftersdb`.`competition` (`city_id` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`weight_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`weight_class` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`weight_class` (
  `weight_class_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `weight_class_name` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`weight_class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `powerliftersdb`.`age_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`age_class` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`age_class` (
  `age_class_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `age_class_name` VARCHAR(45) NOT NULL DEFAULT '',
  PRIMARY KEY (`age_class_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `age_class_UNIQUE` ON `powerliftersdb`.`age_class` (`age_class_name` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`competition_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`competition_result` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`competition_result` (
  `competition_result_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `powerlifter_id` INT UNSIGNED NOT NULL,
  `competition_id` INT UNSIGNED NOT NULL,
  `place` SMALLINT(3) UNSIGNED NOT NULL DEFAULT 0,
  `participants_number` SMALLINT(4) NOT NULL DEFAULT 0,
  `weight_class_id` INT UNSIGNED NOT NULL,
  `age_class_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`competition_result_id`),
  CONSTRAINT `fk_powerlifter_has_competition_powerlifter`
    FOREIGN KEY (`powerlifter_id`)
    REFERENCES `powerliftersdb`.`powerlifter` (`powerlifter_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_powerlifter_has_competition_competition1`
    FOREIGN KEY (`competition_id`)
    REFERENCES `powerliftersdb`.`competition` (`competition_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competition_result_weight_class1`
    FOREIGN KEY (`weight_class_id`)
    REFERENCES `powerliftersdb`.`weight_class` (`weight_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competition_result_age_class1`
    FOREIGN KEY (`age_class_id`)
    REFERENCES `powerliftersdb`.`age_class` (`age_class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_powerlifter_has_competition_competition1_idx` ON `powerliftersdb`.`competition_result` (`competition_id` ASC);

CREATE INDEX `fk_powerlifter_has_competition_powerlifter_idx` ON `powerliftersdb`.`competition_result` (`powerlifter_id` ASC);

CREATE INDEX `fk_competition_result_weight_class1_idx` ON `powerliftersdb`.`competition_result` (`weight_class_id` ASC);

CREATE INDEX `fk_competition_result_age_class1_idx` ON `powerliftersdb`.`competition_result` (`age_class_id` ASC);


-- -----------------------------------------------------
-- Table `powerliftersdb`.`exersice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`exersice` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`exersice` (
  `exersice_id` INT NOT NULL,
  `exersice_name` VARCHAR(50) NULL,
  PRIMARY KEY (`exersice_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `powerliftersdb`.`exercise_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `powerliftersdb`.`exercise_result` ;

CREATE TABLE IF NOT EXISTS `powerliftersdb`.`exercise_result` (
  `exercise_result_id` INT NOT NULL,
  `result_in_kg` SMALLINT(4) NOT NULL,
  `competition_result_id` INT UNSIGNED NOT NULL,
  `exersice_id` INT NOT NULL,
  PRIMARY KEY (`exercise_result_id`),
  CONSTRAINT `fk_exercise_result_competition_result1`
    FOREIGN KEY (`competition_result_id`)
    REFERENCES `powerliftersdb`.`competition_result` (`competition_result_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exercise_result_exersice1`
    FOREIGN KEY (`exersice_id`)
    REFERENCES `powerliftersdb`.`exersice` (`exersice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_exercise_result_competition_result1_idx` ON `powerliftersdb`.`exercise_result` (`competition_result_id` ASC);

CREATE INDEX `fk_exercise_result_exersice1_idx` ON `powerliftersdb`.`exercise_result` (`exersice_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
